app:
    resource: '@AppBundle/Controller/'
    type: annotation
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin