services:
#    _defaults:
#        autowire: true
#        public: true
    mytel.registry:
        class: AppBundle\Registry\RegistryService

    mytel.request_listener:
        class: AppBundle\EventListener\RequestListener
        arguments: ['@logger', '%debug%', '@router']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: monolog.logger, channel: api }

    mytel.response_listener:
        class: AppBundle\EventListener\ResponseListener
        arguments: ['@logger', '%debug%', '@mytel.registry', '@doctrine.orm.default_entity_manager']
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            - { name: monolog.logger, channel: api }

    mytel.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        arguments: ['@logger']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            - { name: monolog.logger, channel: exception }

    mytel.email_alert_manager:
        class: AppBundle\Service\EmailAlertManager
        arguments: ['@mailer', '@templating', '%mailer_user%', '[]']

    mytel.mytel_manager:
        class: AppBundle\Service\MyTelManager
        arguments: ['@service_container']

    mytel.session_manager:
        class: AppBundle\Service\SessionManager
        arguments: ['@doctrine', '@translator.default', '@mytel.mytel_manager', '@mytel.transaction_manager']
        
    mytel.user_manager:
        class: AppBundle\Service\UserManager
        arguments: ['@fos_user.user_manager', '@security.password_encoder', '@translator.default']
        
    mytel.audit_manager:
        class: AppBundle\Service\AuditManager
        arguments: ['@doctrine', '@request_stack']

    mytel.transaction_manager:
        class: AppBundle\Service\TransactionManager
        arguments: ['@doctrine', '@service_container','@translator.default', '@mytel.mytel_manager', '@mytel.registry', '@mytel.email_alert_manager']

    mytel.twig_extension:
        class: AppBundle\Twig\Extension\AppExtension
        arguments: ['@mytel.mytel_manager']
        public: false
        tags:
            - { name: twig.extension }

    mytel.soap_client_service:
        class: AppBundle\Service\MyTelSoapClientService
        arguments: ['@doctrine','@logger', '@kernel','%mytel_api_config%']
        tags:
            - { name: monolog.logger, channel: mytel }

    mytel.soap_server_service:
        class: AppBundle\Service\MyTelSoapServerService
        public: true
        arguments: ['@service_container','@doctrine','@logger', '@kernel','%mytel_api_config%']
        tags:
            - { name: monolog.logger, channel: mytel }
